controller_frequency: 5.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.5
  acc_lim_trans: 1.0
  max_vel_trans: 1.0
  min_vel_trans: 0.1
  max_vel_x: 1.0
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.57
  min_vel_theta: -1.57

  sim_time: 5.0
  sim_granularity: 0.1
  angular_sim_granularity: 0.5
  path_distance_bias: 8.0
  goal_distance_bias: 0.5
  occdist_scale: 0.1
  twirling_scale: 5.0

  oscillation_reset_dist: 1.0
  oscillation_reset_angle: 0.4

  vx_samples: 10
  vy_samples: 0
  vth_samples: 20

  xy_goal_tolerance: 4.0
  yaw_goal_tolerance: 0.2
