base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:

  max_vel_x: 1.0
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 0.70
  min_vel_trans: 0.13
  
  max_vel_theta: 1.82
  min_vel_theta: 0.1

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

  xy_goal_tolerance: 1.0
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  sim_time: 2.0
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.3

  publish_traj_pc : true
  publish_cost_grid_pc: true
