global_costmap:
  global_frame: utm
  robot_base_frame: base_link

  plugins:
    - {name: static_map, type: "costmap_2d::StaticLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}

  inflation:
    inflation_radius: 4.0
    cost_scaling_factor: 1.5
